<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Godsways-MBP" failures="1" tests="7" name="com.test.InvalidCredentials" time="20.704" errors="1" timestamp="2023-09-12T21:16:48 GMT" skipped="0">
  <testcase classname="com.test.InvalidCredentials" name="passwordAndNoEmail" time="2.942"/>
  <system-out/>
  <testcase classname="com.test.InvalidCredentials" name="validEmailInvalidPassword" time="3.712">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.test.InvalidCredentials.validEmailInvalidPassword(InvalidCredentials.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validEmailInvalidPassword -->
  <system-out/>
  <testcase classname="com.test.InvalidCredentials" name="emailAndNoPassword" time="3.361"/>
  <system-out/>
  <testcase classname="com.test.InvalidCredentials" name="invalidEmailValidPassword" time="3.827"/>
  <system-out/>
  <testcase classname="com.test.InvalidCredentials" name="teardown" time="0.347">
    <error message="The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;Godsways-MBP&#039;, ip: &#039;fd02:16e2:276e:ce00:1c5c:dcbb:6011:b0bc%en0&#039;, os.name: &#039;Mac OS X&#039;, os.arch: &#039;x86_64&#039;, os.version: &#039;13.4.1&#039;, java.version: &#039;17.0.7&#039;
Driver info: io.appium.java_client.AppiumDriver
Capabilities {appActivity: com.threesdcl.eadapploginsp..., appPackage: com.threesdcl.eadapploginspa, databaseEnabled: false, desired: {appActivity: com.threesdcl.eadapploginsp..., appPackage: com.threesdcl.eadapploginspa, deviceName: Galaxy S21 FE 5G, newCommandTimeout: 60, platformName: android, platformVersion: 13, udid: R5CRC2405JM}, deviceApiLevel: 33, deviceManufacturer: samsung, deviceModel: SM-G990E, deviceName: R5CRC2405JM, deviceScreenDensity: 480, deviceScreenSize: 1080x2340, deviceUDID: R5CRC2405JM, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 60, pixelRatio: 3, platform: LINUX, platformName: Android, platformVersion: 13, statBarHeight: 97, takesScreenshot: true, udid: R5CRC2405JM, viewportRect: {height: 2099, left: 0, top: 97, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: 29a389ca-a87c-494f-9a51-e4352bd24b7c" type="org.openqa.selenium.UnsupportedCommandException">
      <![CDATA[org.openqa.selenium.UnsupportedCommandException: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Godsways-MBP', ip: 'fd02:16e2:276e:ce00:1c5c:dcbb:6011:b0bc%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.4.1', java.version: '17.0.7'
Driver info: io.appium.java_client.AppiumDriver
Capabilities {appActivity: com.threesdcl.eadapploginsp..., appPackage: com.threesdcl.eadapploginspa, databaseEnabled: false, desired: {appActivity: com.threesdcl.eadapploginsp..., appPackage: com.threesdcl.eadapploginspa, deviceName: Galaxy S21 FE 5G, newCommandTimeout: 60, platformName: android, platformVersion: 13, udid: R5CRC2405JM}, deviceApiLevel: 33, deviceManufacturer: samsung, deviceModel: SM-G990E, deviceName: R5CRC2405JM, deviceScreenDensity: 480, deviceScreenSize: 1080x2340, deviceUDID: R5CRC2405JM, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 60, pixelRatio: 3, platform: LINUX, platformName: Android, platformVersion: 13, statBarHeight: 97, takesScreenshot: true, udid: R5CRC2405JM, viewportRect: {height: 2099, left: 0, top: 97, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: 29a389ca-a87c-494f-9a51-e4352bd24b7c
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:45)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:442)
at com.test.BaseClass.teardown(BaseClass.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:404)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- teardown -->
  <system-out/>
  <testcase classname="com.test.InvalidCredentials" name="invalidEmailInvalidPassword" time="4.278"/>
  <system-out/>
  <testcase classname="com.test.InvalidCredentials" name="noEmailAndPassword" time="2.237"/>
  <system-out/>
</testsuite> <!-- com.test.InvalidCredentials -->
